# Generated by Django 4.2 on 2025-05-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0007_eventresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает проверки'), ('accepted', 'Принят'), ('rejected', 'Отклонён')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='recurrence',
            field=models.CharField(choices=[('none', 'Без повторения'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('biweekly', 'Раз в 2 недели'), ('monthly', 'Ежемесячно')], default='none', max_length=10),
        ),
    ]
